Repository dnd-side-project/dnd-12th-5-frontend, pull requests merged in 2025-03, with the labels that each got.

#105 refactor: 예림님 피드백 1번 - eslintrc파일 수정
  .eslintrc.json
  src/app/giftbag/list/[giftBagId]/page.tsx
  src/app/home/page.tsx
  src/app/kakao/callback/page.tsx
  src/components/gift-upload/GiftForm.tsx
  src/components/ui/dialog.tsx
  src/components/ui/textarea.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/hooks/api/useDeliveryGiftBag.ts
  src/lib/utils.ts
Labels: 🐞 BugFix, 🔨 Refactor

#106 refactor: 유틸 및 커스텀 훅 분리
  .github/ISSUE_TEMPLATE/✅-이슈-생성-템플릿.md
  .github/pull_request_template.md
  .prettierrc
  components.json
  src/app/giftbag/[id]/step1.tsx
  src/app/giftbag/[id]/step3.tsx
  src/app/giftbag/delivery/step2.tsx
  src/app/giftbag/delivery/step3.tsx
  src/app/giftbag/list/[giftBagId]/page.tsx
  src/app/home/page.tsx
  src/app/kakao/callback/page.tsx
  src/app/setting/notice/.gitkeep
  src/constants/constants.ts
  src/data/deliveryCharacterData.ts
  src/hooks/.gitkeep
  src/hooks/useDynamicTitle.ts
  src/hooks/useResetStore.ts
  src/layout/Header.tsx
  src/pages/.gitkeep
  src/utils/utils.ts
Labels: 🔨 Refactor

#107 refactor: 아이콘 컴포넌트 생성 외 리팩토링
  src/app/auth/login/page.tsx
  src/app/giftbag/[id]/step1.tsx
  src/app/giftbag/[id]/step2.tsx
  src/app/giftbag/[id]/step3.tsx
  src/app/giftbag/delivery/step1.tsx
  src/app/giftbag/delivery/step2.tsx
  src/app/giftbag/delivery/step3.tsx
  src/app/giftbag/list/[giftBagId]/answer/page.tsx
  src/app/giftbag/list/[giftBagId]/page.tsx
  src/app/giftbag/list/page.tsx
  src/app/home/page.tsx
  src/app/setting/account/page.tsx
  src/app/setting/page.tsx
  src/components/common/Card.tsx
  src/components/common/CharacterCountInput.tsx
  src/components/common/Chip.tsx
  src/components/common/DeliveryCard.tsx
  src/components/common/ErrorMessage.tsx
  src/components/common/Icon.tsx
  src/components/common/KakaoLoginButton.tsx
  src/components/common/LinkButton.tsx
  src/components/common/Onboarding.tsx
  src/components/gift-upload/ChipList.tsx
  src/components/gift-upload/CustomTextArea.tsx
  src/components/gift-upload/GiftBoxDrawer.tsx
  src/components/gift-upload/GiftForm.tsx
  src/components/gift-upload/ImageCard.tsx
  src/components/gift-upload/InputLink.tsx
  src/components/gift-upload/InputReason.tsx
  src/components/gift-upload/UploadImageList.tsx
  src/components/giftbag/AnswerChip.tsx
  src/components/giftbag/Chip.tsx
  src/components/giftbag/DetailGiftBox.tsx
  src/components/giftbag/GiftBagList.tsx
  src/components/giftbag/GiftList.tsx
  src/components/giftbag/ReceiveGiftList.tsx
  src/components/giftbag/SelectedGiftBag.tsx
  src/components/myGiftbag/CopyLinkButton.tsx
  src/components/myGiftbag/MyCardList.tsx
  src/components/myGiftbag/MyGiftBagCard.tsx
  src/components/myGiftbag/MyGiftBagStatusChip.tsx
  src/constants/constants.ts
  src/data/deliveryCharacterData.ts
  src/hooks/api/useDeliveryGiftBag.ts
  src/layout/Header.tsx
  src/types/components/types.ts
  src/types/constants/types.ts
  src/types/giftbag/types.ts
Labels: ✨ Feature, 🔨 Refactor

#120 feat: 툴팁 나오는 타이밍 수정
  src/components/giftbag/GiftList.tsx
Labels: ✨ Feature, 🔨 Refactor

#121 style: 선물 상자 채우기 - 이미지 border color 수정
  src/components/common/CharacterCountInput.tsx
  src/components/gift-upload/InputLink.tsx
  src/components/gift-upload/InputReason.tsx
  src/components/gift-upload/UploadImageList.tsx
Labels: 🎨 Html & CSS
