Repository dnd-side-project/dnd-12th-5-frontend, pull requests merged in 2025-04, with the labels that each got.

#123 feat: 선물 사진 순서 바꾸기 기능 구현
  package-lock.json
  package.json
  src/app/giftbag/[id]/step2.tsx
  src/components/gift-upload/ImageCard.tsx
  src/components/gift-upload/SortableImageWrapper.tsx
  src/components/gift-upload/UploadImageList.tsx
  src/components/giftbag/GiftList.tsx
  src/types/components/types.ts
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#126 feat: 배달 페이지 내 x 버튼 클릭 시 home으로 이동
  src/layout/Header.tsx
Labels: ✨ Feature

#127 design: mobile safari 호환성을 위해 100vh에서 100svh로 변경
  src/app/layout.tsx
Labels: 🐞 BugFix, 🎨 Html & CSS

#129 feat: 이미지 개수 관련 메세지 text 띄우기
  src/components/gift-upload/GiftForm.tsx
Labels: ✨ Feature, 🎨 Html & CSS

#132 feat: 보따리 채우기 - 뒤로가기 관련 수정
  src/app/giftbag/list/[giftBagId]/page.tsx
  src/app/giftbag/list/page.tsx
  src/components/gift-upload/GiftBoxDrawer.tsx
  src/components/ui/drawer.tsx
  src/layout/GoToHomeDrawer.tsx
  src/layout/Header.tsx
Labels: ✨ Feature, 🔨 Refactor, 🎨 Html & CSS

#137 bug: drawer 버그 해결
  src/components/bundle/GiftList.tsx
  src/components/gift-upload/BundleDrawer.tsx
  src/components/gift-upload/DeleteBundleDrawer.tsx
  src/components/gift-upload/GiftBoxDrawer.tsx
  src/types/components/types.ts
Labels: 🐞 BugFix

#138 feat: 카카오톡 공유하기 기능
  global.d.ts
  src/app/bundle/delivery/step3.tsx
  src/app/bundle/list/[bundleId]/page.tsx
  src/app/layout.tsx
  src/components/KakaoInitScript.tsx
Labels: ✨ Feature

#139 style: 선물 박스 채우기 버튼 위치 수정
  .prettierrc
  package-lock.json
  package.json
  src/app/auth/login/page.tsx
  src/app/bundle/[id]/page.tsx
  src/app/bundle/[id]/step1.tsx
  src/app/bundle/[id]/step2.tsx
  src/app/bundle/[id]/step3.tsx
  src/app/bundle/add/page.tsx
  src/app/bundle/delivery/page.tsx
  src/app/bundle/delivery/step1.tsx
  src/app/bundle/delivery/step2.tsx
  src/app/bundle/delivery/step3.tsx
  src/app/bundle/list/[bundleId]/[giftId]/page.tsx
  src/app/bundle/list/[bundleId]/answer/page.tsx
  src/app/bundle/list/[bundleId]/page.tsx
  src/app/bundle/list/page.tsx
  src/app/bundle/name/page.tsx
  src/app/bundle/select/page.tsx
  src/app/gift-upload/page.tsx
  src/app/home/page.tsx
  src/app/kakao/callback/page.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/setting/account/page.tsx
  src/app/setting/notice/page.tsx
  src/app/setting/page.tsx
  src/components/bundle/AnswerChip.tsx
  src/components/bundle/BundleForm.tsx
  src/components/bundle/BundleList.tsx
  src/components/bundle/Chip.tsx
  src/components/bundle/DetailGiftBox.tsx
  src/components/bundle/GiftList.tsx
  src/components/bundle/ReceiveGiftList.tsx
  src/components/bundle/SelectedBundle.tsx
  src/components/common/Card.tsx
  src/components/common/CharacterCountInput.tsx
  src/components/common/Chip.tsx
  src/components/common/DeliveryCard.tsx
  src/components/common/ErrorMessage.tsx
  src/components/common/KakaoLoginButton.tsx
  src/components/common/LinkButton.tsx
  src/components/common/Loading.tsx
  src/components/common/Onboarding.tsx
  src/components/gift-upload/BundleDrawer.tsx
  src/components/gift-upload/CustomTextArea.tsx
  src/components/gift-upload/DeleteBundleDrawer.tsx
  src/components/gift-upload/GiftForm.tsx
  src/components/gift-upload/ImageCard.tsx
  src/components/gift-upload/InputLink.tsx
  src/components/gift-upload/InputReason.tsx
  src/components/gift-upload/UploadImageList.tsx
  src/components/myBundle/CopyLinkButton.tsx
  src/components/myBundle/MyBundleCard.tsx
  src/components/myBundle/MyBundleNameChip.tsx
  src/components/myBundle/MyBundleStatusChip.tsx
  src/components/ui/dialog.tsx
  src/components/ui/drawer.tsx
  src/layout/GoToHomeDrawer.tsx
  src/layout/Header.tsx
Labels: 🎨 Html & CSS

#146 feat: 선물 박스 채우기 - 이미지 용량 제한 추가
  src/components/gift-upload/GiftForm.tsx
  src/components/gift-upload/SortableImageWrapper.tsx
  src/components/gift-upload/UploadImageList.tsx
  src/constants/constants.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Html & CSS

#147 refactor: 선물 상자 최소 개수 수정
  src/app/bundle/add/page.tsx
  src/constants/constants.ts
  src/layout/Header.tsx
Labels: 🔨 Refactor

#150 style: 헤더 z-index 수정
  src/layout/Header.tsx
Labels: 🔨 Refactor, 🎨 Html & CSS

#151 refactor: 선물 상자 채우기 - 임시저장하지 않고 뒤로가기 버튼 누른 경우 수정
  src/ queries/useDeleteMyBundle.ts
  src/ queries/useDeliveryBundle.ts
  src/ queries/useFillGift.ts
  src/ queries/useGiftDetail.ts
  src/ queries/useMyBundleDetail.ts
  src/ queries/useMyBundles.ts
  src/ queries/useMyBundlesPreview.ts
  src/app/bundle/delivery/step2.tsx
  src/app/bundle/list/[bundleId]/[giftId]/page.tsx
  src/app/bundle/list/[bundleId]/page.tsx
  src/app/bundle/list/page.tsx
  src/app/home/page.tsx
  src/hooks/useTempSaveBundle.ts
  src/layout/GoToHomeDrawer.tsx
  src/layout/Header.tsx
  src/types/bundle/types.ts
Labels: ✨ Feature, 🔨 Refactor

#158 style: 토스트 스타일 변경
  src/app/bundle/[id]/step2.tsx
  src/app/bundle/delivery/step3.tsx
  src/app/bundle/list/[bundleId]/page.tsx
  src/app/kakao/callback/page.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/hooks/useTempSaveBundle.ts
  tailwind.config.ts
Labels: 🔨 Refactor, 🎨 Html & CSS

#163 style: 답변 페이지 퍼블리싱
  src/api/bundle/api.ts
  src/app/bundle/[id]/step2.tsx
  src/components/bundle/DetailGiftBox.tsx
  src/components/bundle/ReceiveAnswerChip.tsx
  src/components/bundle/ReceiveAnswerChipList.tsx
  src/constants/constants.ts
  src/layout/Header.tsx
  src/types/bundle/types.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Html & CSS

#171 api: 답변 전송 api 수정
  src/api/bundle/api.ts
  src/app/bundle/[id]/step2.tsx
Labels: 📭 API

#172 feat: 선물 박스 채우기 - 보따리 이름 수정
  public/icons/edit.svg
  src/hooks/useDynamicTitle.ts
  src/layout/Header.tsx
Labels: ✨ Feature, 🎨 Html & CSS

#173 Refactor: 보따리 목록 페이지 경로명 수정 (/bundle/list -> /my-bundles)
  src/app/bundle/select/page.tsx
  src/app/home/page.tsx
  src/app/my-bundles/[bundleId]/[giftId]/page.tsx
  src/app/my-bundles/[bundleId]/answer/page.tsx
  src/app/my-bundles/[bundleId]/page.tsx
  src/app/my-bundles/page.tsx
  src/components/bundle/BundleList.tsx
  src/components/common/Card.tsx
  src/components/gift-upload/BundleDrawer.tsx
  src/components/myBundle/MyCardList.tsx
  src/layout/Header.tsx
  src/middleware.ts
  src/types/bundle/types.ts
  src/types/components/types.ts
Labels: 🔨 Refactor

#174 Feat: home 데이터 추가 (name, date)
  public/img/main_graphic.svg
  src/app/bundle/select/page.tsx
  src/app/home/page.tsx
  src/components/myBundle/MyCardList.tsx
  src/types/bundle/types.ts
  src/types/components/types.ts
  src/utils/dateFormatter.ts
Labels: ✨ Feature, 🎨 Html & CSS

#177 feat: 내가 만든 보따리 상세 페이지 수정
  src/app/bundle/[id]/page.tsx
  src/app/bundle/delivery/step3.tsx
  src/app/bundle/select/page.tsx
  src/app/my-bundles/[bundleId]/page.tsx
  src/components/common/ShareSection.tsx
  src/components/myBundle/MyBundleCard.tsx
  src/components/myBundle/MyBundleNameChip.tsx
  src/components/myBundle/MyBundleStatusChip.tsx
  src/types/bundle/types.ts
Labels: ✨ Feature

#184 fix: 내가 만든 보따리 상세 페이지 로직 수정
  src/app/my-bundles/[bundleId]/page.tsx
  src/queries/useDraftBundleGiftsQuery.ts
Labels: 🐞 BugFix

#188 fix: Image 태그 관련 warning 해결
  src/app/auth/login/page.tsx
  src/app/home/page.tsx
  src/components/bundle/GiftList.tsx
  src/components/bundle/SelectedBundle.tsx
  src/components/common/Card.tsx
  src/components/common/Icon.tsx
  src/components/common/Onboarding.tsx
Labels: 🐞 BugFix

#189 refactor: 보따리 색상 선택 text 수정
  src/app/bundle/page.tsx
  src/app/bundle/step1.tsx
  src/app/bundle/step2.tsx
  src/app/home/page.tsx
  src/layout/Header.tsx
Labels: 🔨 Refactor

#186 feat: accessToken 재발급 로직 및 자동 로그아웃
  src/api/axiosInstance.ts
Labels: ✨ Feature

#190 bug: 선물 박스 채우기 - 이미지 업로드 버그 수정
  src/components/gift-upload/GiftForm.tsx
  src/components/gift-upload/UploadImageList.tsx
  src/components/ui/toast.tsx
  src/constants/constants.ts
  src/queries/useUploadImageMutation.ts
  src/types/components/types.ts
Labels: 🐞 BugFix, 🔨 Refactor

#192 style: 답변 페이지 재퍼블리싱
  src/app/bundle/[id]/page.tsx
  src/app/bundle/[id]/step2.tsx
  src/components/bundle/CarouselNavigator.tsx
  src/components/bundle/DetailGiftBox.tsx
  src/components/bundle/ReceiveAnswerChip.tsx
  src/types/bundle/types.ts
Labels: 🎨 Html & CSS, 📭 API
