Repository dnd-side-project/dnd-12th-5-frontend, pull requests merged in 2025-02, with the labels that each got.

#17 style: 스타일 관련 기본 세팅
  src/app/fonts/GeistMonoVF.woff
  src/app/fonts/GeistVF.woff
  src/app/fonts/NanumSquareRound.ttf
  src/app/fonts/Pretendard.woff
  src/app/globals.css
  src/app/layout.tsx
  src/components/Header.tsx
  src/components/ui/button.tsx
  src/types/.gitkeep
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Html & CSS

#20 feat: 공통 컴포넌트 헤더 개발
  src/components/Header.tsx
  src/public/icons/arrow_left_large.svg
  src/public/icons/logo.svg
  src/public/icons/setting_large.svg
Labels: ✨ Feature

#18 style: 선물 보따리 만들기 플로우 퍼블리싱
  public/icons/arrow_left_large.svg
  public/icons/logo.svg
  public/icons/setting_large.svg
  public/img/giftBag_blue.svg
  public/img/giftBag_green.svg
  public/img/giftBag_pink.svg
  public/img/giftBag_red.svg
  public/img/giftBag_yellow.svg
  src/app/giftbag/_components/GiftBagList.tsx
  src/app/giftbag/_components/SelectedGiftBag.tsx
  src/app/giftbag/_stores/useStore.ts
  src/app/giftbag/select/page.tsx
  src/components/Card.tsx
  src/components/Header.tsx
  src/public/.gitkeep
Labels: 🎨 Html & CSS

#23 fix: card width 줄어듬 방지
  src/components/Card.tsx
Labels: 🐞 BugFix

#22 style: 선물 보따리 만들기 플로우 퍼블리싱
  public/img/gift_blank_round.svg
  public/img/gift_blank_square.svg
  src/app/giftbag/add/page.tsx
  src/app/giftbag/name/page.tsx
  src/app/giftbag/select/page.tsx
  src/app/layout.tsx
  src/components/common/Card.tsx
  src/components/common/CharacterCountInput.tsx
  src/components/common/Header.tsx
  src/components/giftbag/Chip.tsx
  src/components/giftbag/GiftBagList.tsx
  src/components/giftbag/GiftList.tsx
  src/components/giftbag/SelectedGiftBag.tsx
  src/components/ui/input.tsx
Labels: 🎨 Html & CSS

#24 feat: 메인 페이지 개발
  public/icons/arrow_right_small.svg
  public/img/main_graphic.svg
  src/app/layout.tsx
  src/app/page.tsx
  src/components/MyGiftBagList.tsx
  src/layout/.gitkeep
  src/layout/Header.tsx
Labels: ✨ Feature, 🎨 Html & CSS

#25 style: 선물 보따리 채우기 플로우 퍼블리싱
  package-lock.json
  package.json
  public/icons/btn_erase.svg
  public/icons/image_medium.svg
  public/img/gift_letter_square.svg
  src/app/constants/constants.ts
  src/app/fonts/Pretendard.woff
  src/app/fonts/PretendardVariable.woff2
  src/app/gift-upload/page.tsx
  src/app/giftbag/name/page.tsx
  src/app/layout.tsx
  src/components/common/CharacterCountInput.tsx
  src/components/common/Chip.tsx
  src/components/common/ErrorMessage.tsx
  src/components/gift-upload/ChipList.tsx
  src/components/gift-upload/CustomTextArea.tsx
  src/components/gift-upload/GiftForm.tsx
  src/components/gift-upload/ImageCard.tsx
  src/components/gift-upload/InputLink.tsx
  src/components/gift-upload/InputReason.tsx
  src/components/gift-upload/UploadImageList.tsx
  src/components/giftbag/GiftBagForm.tsx
  src/components/giftbag/GiftBagList.tsx
  src/components/giftbag/GiftList.tsx
  src/components/giftbag/SelectedGiftBag.tsx
  src/components/ui/textarea.tsx
  src/components/ui/tooltip.tsx
  src/stores/gift-upload/useStore.ts
  src/stores/giftbag/useStore.ts
  tailwind.config.ts
Labels: 🎨 Html & CSS

#31 feat: 선물 보따리 만들기 플로우 로직 및 퍼블리싱
  src/app/constants/constants.ts
  src/components/gift-upload/CustomTextArea.tsx
  src/components/gift-upload/GiftBoxDialog.tsx
  src/components/gift-upload/GiftBoxDrawer.tsx
  src/components/gift-upload/InputReason.tsx
  src/components/giftbag/GiftList.tsx
  src/components/giftbag/SelectedGiftBag.tsx
  src/layout/Header.tsx
  src/stores/gift-upload/useStore.ts
  src/stores/giftbag/useStore.ts
  src/types/giftbag/types.ts
Labels: 🐞 BugFix, 🔨 Refactor, 🎨 Html & CSS

#33 style: 선물 보따리 배달하기 페이지 퍼블리싱
  public/icons/kakao_share_button.svg
  public/icons/link_copy_button.svg
  public/img/delivery_1.svg
  src/app/giftbag/delivery/page.tsx
  src/app/giftbag/delivery/step1.tsx
  src/app/giftbag/delivery/step2.tsx
  src/app/giftbag/delivery/step3.tsx
  src/components/common/DeliveryCard.tsx
  src/data/deliveryCharacterData.ts
  src/layout/Header.tsx
Labels: ✨ Feature, 🎨 Html & CSS

#34 feat: 내가 만든 보따리 목록 페이지
  public/icons/check.svg
  public/icons/indicator.svg
  src/app/giftbag/list/page.tsx
  src/app/page.tsx
  src/components/myGiftbag/MyGiftBagCard.tsx
  src/components/myGiftbag/MyGiftBagList.tsx
  src/components/myGiftbag/MyGiftBagStatusChip.tsx
  src/layout/Header.tsx
Labels: ✨ Feature, 🎨 Html & CSS

#38 feat: 헤더 타이틀 넘침 제어
  src/layout/Header.tsx
Labels: ✨ Feature

#42 feat: 로그인 한 경우에만 설정 아이콘이 보이도록 로직 추가
  src/layout/Header.tsx
Labels: ✨ Feature

#43 fix: 편집/완료 버튼 선택 안되는 오류 수정 및 상세 페이지로 리다이렉트 로직 추가
  src/app/giftbag/list/page.tsx
  src/components/myGiftbag/MyGiftBagStatusChip.tsx
  src/layout/Header.tsx
Labels: 🐞 BugFix, ✨ Feature

#50 design: 내가 만든 보따리 상세 페이지 퍼블리싱
  public/img/KakaoTalk_20250210_165219597.jpg
  public/img/KakaoTalk_20250210_165219597_01.jpg
  public/img/KakaoTalk_20250210_165219597_02.jpg
  public/img/KakaoTalk_20250210_165219597_03.jpg
  src/app/giftbag/detail/[id]/page.tsx
  src/app/page.tsx
  src/components/common/Card.tsx
  src/components/myGiftbag/CopyLinkButton.tsx
  src/components/myGiftbag/MyCardList.tsx
  src/components/myGiftbag/MyGiftBagList.tsx
  src/components/myGiftbag/MyGiftBagNameChip.tsx
  src/layout/Header.tsx
Labels: 🎨 Html & CSS

#51 design: 목록 내 status chip 컴포넌트에서 div 태그 -> span 태그로 변경
  src/components/myGiftbag/MyGiftBagStatusChip.tsx
Labels: 🔨 Refactor

#44 design: 상대방이 받아보는 화면 퍼블리싱
  package-lock.json
  package.json
  public/img/gift_letter_square.svg
  src/app/giftbag/[id]/page.tsx
  src/app/giftbag/[id]/step1.tsx
  src/app/giftbag/[id]/step2.tsx
  src/app/giftbag/[id]/step3.tsx
  src/app/giftbag/add/page.tsx
  src/app/giftbag/delivery/step3.tsx
  src/components/common/Loading.tsx
  src/components/gift-upload/GiftForm.tsx
  src/components/gift-upload/InputLink.tsx
  src/components/giftbag/Chip.tsx
  src/components/giftbag/DetailGiftBox.tsx
  src/components/giftbag/GiftList.tsx
  src/components/giftbag/ReciveGiftList.tsx
  src/components/giftbag/SelectedGiftBag.tsx
  src/components/ui/carousel.tsx
  src/types/giftbag/types.ts
Labels: 🎨 Html & CSS

#41 design: 설정 페이지
  public/icons/btn_login_kakao.svg
  src/app/setting/account/page.tsx
  src/app/setting/notice/.gitkeep
  src/app/setting/page.tsx
  src/app/setting/version/.gitkeep
  src/layout/Header.tsx
Labels: 🎨 Html & CSS

#53 design: 결과 페이지 퍼블리싱
  public/icons/arrow_right_large.svg
  src/app/constants/constants.ts
  src/app/giftbag/detail/[id]/answer/page.tsx
  src/components/common/Card.tsx
  src/components/giftbag/AnswerChip.tsx
  src/components/giftbag/DetailGiftBox.tsx
  src/components/myGiftbag/MyCardList.tsx
  src/components/myGiftbag/MyGiftBagNameChip.tsx
Labels: 🎨 Html & CSS

#54 feat: 상대방이 받아보는 페이지 로직 구현
  package-lock.json
  public/icons/arrow_right_large.svg
  public/icons/arrow_right_medium.svg
  public/img/gift_1.jpg
  public/img/gift_2.jpg
  public/img/gift_3_1.jpg
  public/img/gift_3_2.jpg
  public/img/gift_3_3.jpg
  public/img/gift_4.jpg
  public/img/gift_background_round.svg
  public/img/gift_background_square.svg
  src/app/giftbag/[id]/page.tsx
  src/app/giftbag/[id]/step1.tsx
  src/app/giftbag/[id]/step2.tsx
  src/app/giftbag/detail/[id]/answer/page.tsx
  src/app/giftbag/detail/[id]/page.tsx
  src/components/common/Loading.tsx
  src/components/giftbag/DetailGiftBox.tsx
  src/components/giftbag/ReciveGiftList.tsx
  src/components/giftbag/SelectedGiftBag.tsx
  src/components/ui/carousel.tsx
  src/layout/Header.tsx
  src/stores/giftbag/useStore.ts
Labels: ✨ Feature, 🎨 Html & CSS

#58 refactor: 퍼블리싱 및 로직 확인 후 수정
  src/app/giftbag/add/page.tsx
  src/app/giftbag/name/page.tsx
  src/app/page.tsx
  src/components/common/DeliveryCard.tsx
  src/components/gift-upload/GiftBoxDrawer.tsx
  src/components/gift-upload/GiftForm.tsx
  src/components/giftbag/GiftBagForm.tsx
  src/components/giftbag/GiftList.tsx
  src/layout/Header.tsx
Labels: ✨ Feature, 🔨 Refactor, 🎨 Html & CSS

#60 design: 내가 담았던 선물 상세 페이지
  src/app/giftbag/list/[giftbagId]/[giftId]/page.tsx
  src/components/common/LinkButton.tsx
  src/data/giftbagData.ts
Labels: 🎨 Html & CSS

#62 feat: 내가 만든 보따리 상세 - 삭제하기 drawer 추가
  src/app/giftbag/list/[giftbagId]/page.tsx
  src/components/myGiftbag/CopyLinkButton.tsx
  src/components/myGiftbag/MyCardList.tsx
  src/components/myGiftbag/MyGiftBagNameChip.tsx
  src/data/giftbagData.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Html & CSS

#63 design: 디자인 변경에 따른 수정
  public/img/chichi_blue.svg
  public/img/chichi_green.svg
  public/img/chichi_pink.svg
  public/img/chichi_red.svg
  public/img/chichi_yellow.svg
  public/img/giftBag_blue.svg
  public/img/giftBag_green.svg
  public/img/giftBag_pink.svg
  public/img/giftBag_red.svg
  public/img/giftBag_yellow.svg
  public/img/gift_background_round.svg
  public/img/gift_background_square.svg
  public/img/gift_blank_round.svg
  public/img/gift_blank_square.svg
  public/img/gift_letter_round.svg
  public/img/gift_letter_square.svg
  public/img/gift_no_letter_round.svg
  public/img/gift_no_letter_square.svg
  public/img/hearty_blue.svg
  public/img/hearty_green.svg
  public/img/hearty_pink.svg
  public/img/hearty_red.svg
  public/img/hearty_yellow.svg
  public/img/max_blue.svg
  public/img/max_green.svg
  public/img/max_pink.svg
  public/img/max_red.svg
  public/img/max_yellow.svg
  public/img/pori_blue.svg
  public/img/pori_green.svg
  public/img/pori_pink.svg
  public/img/pori_red.svg
  public/img/pori_yellow.svg
  src/app/giftbag/[id]/step3.tsx
  src/app/giftbag/delivery/step2.tsx
  src/components/giftbag/GiftBagForm.tsx
  src/layout/Header.tsx
  src/stores/giftbag/useStore.ts
Labels: ✨ Feature, 🎨 Html & CSS

#35 feat: 카카오 소셜 로그인 로직 구현 및 통신
  src/app/kakao/callback/page.tsx
Labels: ✨ Feature, 📭 API

#74 feat: 상대방이 받아보는 페이지 로직 수정
  public/favicon/favicon-128x128.png
  public/favicon/favicon-16x16.png
  public/favicon/favicon-196x196.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon-96x96.png
  public/img/background_union.svg
  public/img/chichi_blue.svg
  public/img/chichi_green.svg
  public/img/chichi_pink.svg
  public/img/chichi_red.svg
  public/img/chichi_yellow.svg
  public/img/delivery_1.svg
  public/img/delivery_2.svg
  public/img/delivery_3.svg
  public/img/delivery_4.svg
  public/img/max_blue.svg
  public/img/max_green.svg
  public/img/max_pink.svg
  public/img/max_red.svg
  public/img/max_yellow.svg
  src/app/favicon.ico
  src/app/giftbag/[id]/page.tsx
  src/app/giftbag/[id]/step1.tsx
  src/app/giftbag/[id]/step2.tsx
  src/app/giftbag/[id]/step3.tsx
  src/app/giftbag/delivery/step2.tsx
  src/app/layout.tsx
  src/components/common/Chip.tsx
  src/components/giftbag/DetailGiftBox.tsx
  src/components/giftbag/GiftBagList.tsx
  src/components/giftbag/ReceiveGiftList.tsx
  src/components/giftbag/SelectedGiftBag.tsx
  src/data/deliveryCharacterData.ts
  src/stores/giftbag/useStore.ts
  src/types/giftbag/types.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Html & CSS

#75 내가 만든 보따리 관련 페이지
  next.config.mjs
  public/img/main_graphic.svg
  src/app/giftbag/list/[giftbagId]/[giftId]/page.tsx
  src/app/giftbag/list/[giftbagId]/page.tsx
  src/app/giftbag/list/page.tsx
  src/app/home/page.tsx
  src/app/providers.tsx
  src/components/common/Card.tsx
  src/components/myGiftbag/MyCardList.tsx
  src/components/myGiftbag/MyGiftBagCard.tsx
  src/constants/constants.ts
  src/data/giftbagData.ts
  src/hooks/api/useMyGiftBags.ts
  src/layout/Header.tsx
  src/stores/giftbag/useStore.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html & CSS, 📭 API

#81 feat: 이미지 업로드 api 연결
  next.config.mjs
  src/api/gift-upload/api.ts
  src/components/common/Card.tsx
  src/components/gift-upload/GiftBoxDrawer.tsx
  src/components/gift-upload/GiftForm.tsx
  src/components/gift-upload/UploadImageList.tsx
  src/components/giftbag/GiftList.tsx
  src/stores/gift-upload/useStore.ts
  src/types/giftbag/types.ts
Labels: ✨ Feature, 🎨 Html & CSS, 📭 API

#82 feat: 보따리 생성 api 연결
  src/api/giftbag/api.ts
  src/app/giftbag/delivery/step1.tsx
  src/app/giftbag/delivery/step2.tsx
  src/components/common/DeliveryCard.tsx
  src/constants/constants.ts
Labels: ✨ Feature, 🎨 Html & CSS, 📭 API

#80 feat: home api 통신
  src/app/giftbag/list/[giftbagId]/page.tsx
  src/app/home/page.tsx
  src/components/myGiftbag/MyCardList.tsx
  src/hooks/api/useMyGiftBagPreview.ts
  src/stores/giftbag/useStore.ts
Labels: 🔨 Refactor, 📭 API

#83 fix: 이미지 업로드 관련 로직 수정
  src/components/gift-upload/CustomTextArea.tsx
  src/components/gift-upload/GiftForm.tsx
  src/components/gift-upload/UploadImageList.tsx
  src/types/gift-upload/types.ts
Labels: 🐞 BugFix, 🔨 Refactor

#85 feat: 내가만든보따리 관련 api
  src/app/giftbag/list/[giftbagId]/[giftId]/page.tsx
  src/app/giftbag/list/[giftbagId]/page.tsx
  src/app/giftbag/list/page.tsx
  src/hooks/api/useDeleteMyGiftBag.ts
  src/hooks/api/useGiftDetail.ts
  src/hooks/api/useMyGiftBagDetail.ts
Labels: 📭 API

#84 feat: 보따리 생성 api 플로우 수정
  src/api/giftbag/api.ts
  src/app/giftbag/add/page.tsx
  src/app/giftbag/delivery/step2.tsx
  src/components/giftbag/GiftList.tsx
  src/layout/Header.tsx
  src/types/giftbag/types.ts
Labels: ✨ Feature, 🔨 Refactor, 📭 API

#88 Feat: 배달부 설정 api 연결, 링크 복사 기능
  src/app/giftbag/delivery/page.tsx
  src/app/giftbag/delivery/step1.tsx
  src/app/giftbag/delivery/step2.tsx
  src/app/giftbag/delivery/step3.tsx
  src/components/common/DeliveryCard.tsx
  src/data/deliveryCharacterData.ts
  src/hooks/api/useDeliveryGiftBag.ts
  src/types/giftbag/types.ts
Labels: ✨ Feature, 📭 API

#93 feat: 보따리 풀어보기 api 연결
  next.config.mjs
  package-lock.json
  package.json
  src/api/giftbag/api.ts
  src/app/giftbag/[id]/page.tsx
  src/app/giftbag/[id]/step2.tsx
  src/app/giftbag/delivery/step3.tsx
  src/app/giftbag/list/[giftbagId]/page.tsx
  src/app/setting/notice/page.tsx
  src/app/setting/page.tsx
  src/app/setting/version/.gitkeep
  src/components/giftbag/ReceiveGiftList.tsx
  src/components/ui/dialog.tsx
  src/layout/Header.tsx
Labels: ✨ Feature, 🎨 Html & CSS, 📭 API

#97 fix: 이미지 캐러셀 오류 수정
  src/app/giftbag/list/[giftbagId]/[giftId]/page.tsx
Labels: 🐞 BugFix

#94 feat: 답변 저장하기 api 연결
  src/api/giftbag/api.ts
  src/app/giftbag/[id]/page.tsx
  src/app/giftbag/[id]/step2.tsx
  src/app/giftbag/list/[giftbagId]/answer/page.tsx
  src/app/setting/page.tsx
  src/components/gift-upload/CustomTextArea.tsx
  src/components/gift-upload/GiftForm.tsx
  src/components/gift-upload/InputReason.tsx
  src/components/giftbag/AnswerChip.tsx
  src/constants/constants.ts
  src/layout/Header.tsx
  src/types/giftbag/types.ts
  src/utils/.gitkeep
  src/utils/utils.ts
Labels: ✨ Feature, 🎨 Html & CSS, 📭 API

#99 Fix: 마저 채우기 관련 api 및 로직 오류
  src/app/giftbag/add/page.tsx
  src/app/giftbag/list/[giftbagId]/[giftId]/page.tsx
  src/app/giftbag/list/[giftbagId]/page.tsx
  src/app/giftbag/list/page.tsx
  src/components/giftbag/GiftList.tsx
  src/hooks/api/useFillGift.ts
  src/layout/Header.tsx
Labels: 🐞 BugFix

#100 feat: 로컬스토리지에 저장해둔 것들 초기화
  src/app/giftbag/list/[giftbagId]/answer/page.tsx
  src/app/home/page.tsx
  src/components/gift-upload/GiftForm.tsx
Labels: ✨ Feature, 🔨 Refactor, 🎨 Html & CSS
