Repository dnd-side-project/dnd-12th-5-frontend, pull requests merged in 2025-05, with the labels that each got.

#201 feat: 임시 저장된 보따리 이름 수정
  src/api/api-url.ts
  src/api/bundle/api.ts
  src/app/layout.tsx
  src/app/my-bundles/[bundleId]/page.tsx
  src/hooks/useDynamicTitle.ts
  src/layout/Header.tsx
  src/queries/useEditDrafeBundleName.ts
Labels: ✨ Feature

#195 fix: 로그인 버그 수정
  src/api/api-url.ts
  src/api/axiosInstance.ts
  src/api/kakao/api.ts
  src/utils/tokenUtils.ts
Labels: 🐞 BugFix

#200 feat: 상세 페이지 헤더에 보따리 이름 표시
  src/app/bundle/delivery/step2.tsx
  src/app/my-bundles/[bundleId]/page.tsx
  src/components/bundle/BundleForm.tsx
  src/hooks/useDynamicTitle.ts
  src/hooks/useResetStore.ts
  src/layout/GoToHomeDrawer.tsx
  src/layout/Header.tsx
  src/queries/useCreateBundleMutation.ts
  src/stores/bundle/useStore.ts
Labels: ✨ Feature

#206 feat: 보따리 이름 최대 길이 값 수정
  src/constants/constants.ts
Labels: ✨ Feature

#207 style: 선물 비우기 drawer 간격 및 아이콘 사이즈 수정
  src/components/bundle/add/DeleteBundleDrawer.tsx
  src/constants/constants.ts
  src/types/components/types.ts
Labels: 🎨 Html & CSS

#202 refactor: mutate Error 시 console.log -> toast로 수정
  src/layout/Header.tsx
  src/queries/useDeleteMyBundleMutation.ts
  src/queries/useDeliveryCharacterMutation.ts
  src/queries/useEditDraftBundleNameMutation.ts
  src/queries/useUploadImageMutation.ts
Labels: 🔨 Refactor

#203 style: 답변 대기 중인 보따리의 상세 페이지 내 공유 섹션 위치 하단 고정 및 자잘한 warning 해결
  src/app/my-bundles/[bundleId]/page.tsx
  src/app/my-bundles/page.tsx
  src/hooks/useDynamicTitle.ts
Labels: 🐞 BugFix, 🎨 Html & CSS

#208 style: 헤더에 title 풀네임 다 표시되도록 수정, 보따리 목록 카드에서는 말줄임 추가
  src/components/myBundle/MyBundleCard.tsx
  src/layout/Header.tsx
Labels: 🎨 Html & CSS

#215 [Style] 답변 선택 페이지 헤더 text 추가
  src/layout/Header.tsx
Labels: 🎨 Html & CSS

#209 style: 전반적인 스타일 수정
  src/app/bundle/add/page.tsx
  src/app/bundle/delivery/step2.tsx
  src/app/bundle/step1.tsx
  src/app/bundle/step2.tsx
  src/app/my-bundles/[bundleId]/[giftId]/page.tsx
  src/app/my-bundles/[bundleId]/page.tsx
  src/app/my-bundles/page.tsx
  src/app/setting/account/page.tsx
  src/components/common/DeliveryCard.tsx
  src/components/common/ShareSection.tsx
  src/components/myBundle/CopyLinkButton.tsx
  src/components/myBundle/MyBundleCard.tsx
  src/components/myBundle/MyBundleStatusChip.tsx
  src/components/myBundle/MyCardList.tsx
  src/layout/Header.tsx
Labels: 🎨 Html & CSS

#216 feat: 배달 페이지 로딩 추가
  src/app/bundle/delivery/step3.tsx
  tailwind.config.ts
Labels: ✨ Feature

#218 feat: 카카오톡 공유하기 버튼 수정
  src/components/common/ShareSection.tsx
Labels: ✨ Feature

#219 feat: 보따리 결과 페이지의 title 변경
  src/hooks/useDynamicTitle.ts
Labels: ✨ Feature

#221 feat: 보따리 채우기 페이지 - 툴팁이 사라지지 않도록 구현
  src/components/bundle/ReceiveGiftList.tsx
  src/components/bundle/add/CustomTooltipArrow.tsx
  src/components/bundle/add/GiftList.tsx
Labels: 🎨 Html & CSS

#223 fix: 보따리 만들러 가기 버튼 link 수정
  src/app/my-bundles/page.tsx
Labels: 🐞 BugFix

#224 fix: UTC → KST로 보정
  src/utils/dateFormatter.ts
Labels: 🐞 BugFix

#225 fix: 배달 준비 중 로딩 페이지에서 close 버튼 숨기기
  src/app/bundle/delivery/step3.tsx
  src/layout/Header.tsx
  src/stores/bundle/useStore.ts
Labels: 🐞 BugFix

#227 fix: 보따리 최초 생성 상태를 전역 상태로 관리
  src/app/home/page.tsx
  src/app/my-bundles/[bundleId]/page.tsx
  src/app/my-bundles/page.tsx
  src/hooks/bundle/add/useHandleCreateBundleClick.ts
  src/hooks/useResetStore.ts
  src/layout/Header.tsx
  src/stores/bundle/useStore.ts
Labels: 🐞 BugFix

#229 feat: 회원 탈퇴 기능
  src/api/api-url.ts
  src/api/kakao/api.ts
  src/app/setting/account/page.tsx
  src/queries/useDeleteUserMutation.ts
Labels: ✨ Feature

#235 bug: 임시저장 직후 이름 수정이 안되는 버그 해결
  public/img/gift_1.jpg
  public/img/gift_2.jpg
  public/img/gift_3_1.jpg
  public/img/gift_3_2.jpg
  public/img/gift_3_3.jpg
  public/img/gift_4.jpg
  src/layout/Header.tsx
  src/queries/useEditDraftBundleNameMutation.ts
Labels: 🐞 BugFix

#236 refactor: type 및 api 분리
  src/api/api-url.ts
  src/api/axiosInstance.ts
  src/api/bundle/api.ts
  src/api/my-bundle/api.ts
  src/app/bundle/[id]/page.tsx
  src/app/bundle/[id]/step2.tsx
  src/app/bundle/add/page.tsx
  src/app/bundle/delivery/step2.tsx
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/my-bundles/[bundleId]/answer/page.tsx
  src/app/my-bundles/[bundleId]/page.tsx
  src/app/my-bundles/page.tsx
  src/app/setting/account/page.tsx
  src/components/myBundle/MyBundleCard.tsx
  src/components/myBundle/MyCardList.tsx
  src/hooks/bundle/add/useHandleCreateBundleClick.ts
  src/hooks/useTempSaveBundle.ts
  src/queries/useBundleResultQuery.ts
  src/queries/useBundlesPreviewQuery.ts
  src/queries/useCreateBundleMutation.ts
  src/queries/useDeleteMyBundleMutation.ts
  src/queries/useDeleteUserMutation.ts
  src/queries/useDeliveryCharacterMutation.ts
  src/queries/useEditDraftBundleNameMutation.ts
  src/queries/useGiftDetailQuery.ts
  src/queries/useMyBundleDetailQuery.ts
  src/queries/useMyBundlesQuery.ts
  src/queries/useUpdateBundleMutation.ts
  src/queries/useUploadImageMutation.ts
  src/types/bundle/types.ts
  src/types/components/types.ts
  src/types/my-bundles/types.ts
Labels: 🔨 Refactor

#232 bug: 버그 해결
  src/app/bundle/add/page.tsx
  src/components/bundle/Chip.tsx
  src/components/bundle/ReceiveAnswerChip.tsx
  src/components/bundle/ReceiveAnswerChipList.tsx
  src/components/gift-upload/CustomTextArea.tsx
  src/components/gift-upload/GiftForm.tsx
  src/components/gift-upload/ImageCard.tsx
  src/components/gift-upload/InputReason.tsx
  src/components/gift-upload/UploadImageList.tsx
  src/components/ui/button.tsx
  src/layout/Header.tsx
  src/types/components/types.ts
Labels: 🐞 BugFix

#238 style: 응답 페이지 scrollbar 숨기기
  src/app/bundle/[id]/step2.tsx
Labels: 🎨 Html & CSS

#239 fix: Image is missing required "src" property 해결, alt 속성 수정
  public/icons/erase.svg
  public/icons/kakao_logo.svg
  public/icons/kakao_share_button.svg
  public/icons/link_1.svg
  public/icons/link_2.svg
  public/icons/trash.svg
  src/app/bundle/delivery/step2.tsx
  src/app/bundle/delivery/step3.tsx
  src/app/home/page.tsx
  src/app/my-bundles/[bundleId]/[giftId]/page.tsx
  src/app/my-bundles/[bundleId]/answer/page.tsx
  src/app/my-bundles/[bundleId]/page.tsx
  src/app/my-bundles/page.tsx
  src/app/setting/account/page.tsx
  src/app/setting/page.tsx
  src/components/bundle/DetailGiftBox.tsx
  src/components/bundle/add/BundleDrawer.tsx
  src/components/bundle/add/DeleteBundleDrawer.tsx
  src/components/bundle/add/GiftListDrawer.tsx
  src/components/bundle/add/GiftThumbnailList.tsx
  src/components/common/KakaoLoginButton.tsx
  src/components/common/LinkButton.tsx
  src/components/common/ShareSection.tsx
  src/components/gift-upload/ImageCard.tsx
  src/components/myBundle/CopyLinkButton.tsx
  src/components/myBundle/MyBundleCard.tsx
  src/layout/GoToHomeDrawer.tsx
  src/layout/Header.tsx
Labels: 🐞 BugFix, 🔨 Refactor

#240 feat: 선물 박스 채우기 - 링크 유효성검사 추가
  src/components/common/ErrorMessage.tsx
  src/components/gift-upload/GiftForm.tsx
  src/components/gift-upload/ImageCard.tsx
  src/utils/giftBoxUtils.ts
Labels: ✨ Feature

#247 feat: 답변 선택하기 - 이미지 캐러셀 구현
  public/icons/close_black.svg
  public/icons/close_gray_50.svg
  public/icons/image_carousel.svg
  src/app/my-bundles/[bundleId]/page.tsx
  src/app/my-bundles/page.tsx
  src/app/setting/account/page.tsx
  src/components/bundle/CarouselNavigator.tsx
  src/components/bundle/DetailGiftBox.tsx
  src/components/bundle/ImageCarouselViewer.tsx
  src/components/bundle/add/BundleDrawer.tsx
  src/components/bundle/add/DeleteBundleDrawer.tsx
  src/components/bundle/add/GiftListDrawer.tsx
  src/components/common/CarouselNavigator.tsx
  src/components/common/ImageCarouselButton.tsx
  src/layout/GoToHomeDrawer.tsx
  src/layout/Header.tsx
  src/types/components/types.ts
Labels: ✨ Feature

#248 feat: '/' 이동을 위한 Link 추가
  src/layout/Header.tsx
Labels: ✨ Feature

#249 release: Merge dev → main for production
  public/icons/close_black.svg
  public/icons/close_gray_50.svg
  public/icons/image_carousel.svg
  public/icons/kakao_circle_logo.svg
  src/app/my-bundles/[bundleId]/page.tsx
  src/app/my-bundles/page.tsx
  src/app/setting/account/page.tsx
  src/components/bundle/CarouselNavigator.tsx
  src/components/bundle/DetailGiftBox.tsx
  src/components/bundle/ImageCarouselViewer.tsx
  src/components/bundle/add/BundleDrawer.tsx
  src/components/bundle/add/DeleteBundleDrawer.tsx
  src/components/bundle/add/GiftListDrawer.tsx
  src/components/common/CarouselNavigator.tsx
  src/components/common/ImageCarouselButton.tsx
  src/components/common/ShareSection.tsx
  src/layout/GoToHomeDrawer.tsx
  src/layout/Header.tsx
  src/middleware.ts
  src/types/components/types.ts
Labels: 🌏 Deploy

#253 bug: 0509회의때 정리한 수정사항
  public/icons/complete_blue.svg
  public/img/bundle_error_character.svg
  src/api/bundle/api.ts
  src/app/bundle/[id]/page.tsx
  src/app/bundle/[id]/step1.tsx
  src/app/bundle/[id]/step2.tsx
  src/app/my-bundles/[bundleId]/answer/page.tsx
  src/app/my-bundles/[bundleId]/page.tsx
  src/components/bundle/AnswerCompleteChip.tsx
  src/components/bundle/DetailGiftBox.tsx
  src/components/bundle/ReceiveAnswerChipList.tsx
  src/components/bundle/ReceiveGiftList.tsx
  src/components/common/BundleErrorPage.tsx
  src/components/gift-upload/GiftForm.tsx
  src/components/gift-upload/UploadImageList.tsx
  src/constants/constants.ts
  src/queries/useAnswerResultQuery.ts
  src/queries/usePostBundleAnswersMutation.ts
  src/queries/useReceiveBundleQuery.ts
  src/stores/bundle/useStore.ts
  src/types/bundle/types.ts
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#255 feat: open graph 구현
  .eslintrc.json
  src/api/bundle/api.ts
  src/api/gift-upload/api.ts
  src/api/kakao/api.ts
  src/api/my-bundle/api.ts
  src/app/layout.tsx
  src/components/bundle/DetailGiftBox.tsx
  src/components/bundle/SelectedBundle.tsx
  src/components/bundle/add/BundleDrawer.tsx
  src/components/bundle/add/GiftList.tsx
  src/components/bundle/add/GiftThumbnailList.tsx
  src/components/gift-upload/ChipList.tsx
  src/components/gift-upload/CustomTextArea.tsx
  src/components/gift-upload/GiftForm.tsx
  src/components/gift-upload/ImageCard.tsx
  src/components/gift-upload/InputLink.tsx
  src/components/gift-upload/InputReason.tsx
  src/components/gift-upload/UploadImageList.tsx
  src/components/myBundle/MyBundleCard.tsx
  src/queries/useMyBundleDetailQuery.ts
  src/types/bundle/types.ts
Labels: 🐞 BugFix, ✨ Feature

#257 refactor: font weight 수정
  src/app/layout.tsx
Labels: 🔨 Refactor

#256 feat: survey drawer 구현
  public/icons/face-bad.svg
  public/icons/face-good.svg
  public/icons/face-ok.svg
  src/api/api-url.ts
  src/api/survey/api.ts
  src/app/home/page.tsx
  src/components/survey/SurveyDrawer.tsx
  src/queries/useIsSurveyTargetQuery.ts
  src/queries/useSurveyAnswerMutation.ts
Labels: ✨ Feature

#258 release: Merge dev → main for production
  .eslintrc.json
  public/icons/face-bad.svg
  public/icons/face-good.svg
  public/icons/face-ok.svg
  src/api/api-url.ts
  src/api/bundle/api.ts
  src/api/gift-upload/api.ts
  src/api/kakao/api.ts
  src/api/my-bundle/api.ts
  src/api/survey/api.ts
  src/app/home/page.tsx
  src/app/layout.tsx
  src/components/bundle/DetailGiftBox.tsx
  src/components/bundle/SelectedBundle.tsx
  src/components/bundle/add/BundleDrawer.tsx
  src/components/bundle/add/GiftList.tsx
  src/components/bundle/add/GiftThumbnailList.tsx
  src/components/gift-upload/ChipList.tsx
  src/components/gift-upload/CustomTextArea.tsx
  src/components/gift-upload/GiftForm.tsx
  src/components/gift-upload/ImageCard.tsx
  src/components/gift-upload/InputLink.tsx
  src/components/gift-upload/InputReason.tsx
  src/components/gift-upload/UploadImageList.tsx
  src/components/myBundle/MyBundleCard.tsx
  src/components/survey/SurveyDrawer.tsx
  src/queries/useIsSurveyTargetQuery.ts
  src/queries/useMyBundleDetailQuery.ts
  src/queries/useSurveyAnswerMutation.ts
  src/types/bundle/types.ts
Labels: 🌏 Deploy

#259 Refactor/drawer
  src/api/survey/api.ts
  src/app/home/page.tsx
  src/app/my-bundles/page.tsx
  src/components/myBundle/MyBundleDeleteDrawer.tsx
Labels: 🔨 Refactor
